@extends('layouts.LOUser.app')
@section('content')

    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css" integrity="sha256-p4NxAoJBhIIN+hmNHrzRCf9tD/miZyoHS5obTRR9BMY=" crossorigin="" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.7.1/leaflet.css"/>
    <style>
         #map{
            height: 100vh;
            width: 100%;
         }
    </style>
</head>
<body>
    <div class="container">
    <div id="map"></div>
    </div>
</body>
</html>
<script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js" integrity="sha256-20nQCchB9co0qIjJZRGuk2/Z9VM+kNiyxNV1lvTlZBo=" crossorigin=""></script>

<script>
    var map = L.map('map',{
        dragging: true 
    }).setView([18.4905,122.1285], 13);

    L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{
    }).addTo(map);
    
    map.setZoom(12);

    var grassMarker = L.marker([18.4599,122.1396]).addTo(map);
       // Image URL generated by Laravel's asset helper
var imageUrl = "{{ asset('seapics/Seagrass.jpg') }}";
var popupContent = `<b>Sea Grass</b><br><img src="${imageUrl}"  style="width:100px;">`;

grassMarker.bindPopup(popupContent, { closeButton: false });

// Add click event listener to the Neptune marker
grassMarker.on('click', function() {
    // Redirect to the specified route
    window.open("https://example.com", "_blank");  // Replace with your URL
});

// Add mouseover event listener to the Neptune marker
grassMarker.on('mouseover', function() {
    grassMarker.openPopup();
});

// Add mouseout event listener to the Neptune marker
grassMarker.on('mouseout', function() {
    grassMarker.closePopup();
});

        //sample Eelgrass
        var EelgrassMarker = L.marker([18.5169,122.1407]).addTo(map);
    // Image URL generated by Laravel's asset helper
var imageUrl = "{{ asset('seapics/Eelgrass.jpg') }}";
var popupContent = `<b>Eelgrass</b><br><img src="${imageUrl}"  style="width:100px;">`;

EelgrassMarker.bindPopup(popupContent, { closeButton: false });

// Add click event listener to the Neptune marker
EelgrassMarker.on('click', function() {
    // Redirect to the specified route
    window.open("https://example.com", "_blank");  // Replace with your URL
});

// Add mouseover event listener to the Neptune marker
EelgrassMarker.on('mouseover', function() {
    EelgrassMarker.openPopup();
});

// Add mouseout event listener to the Neptune marker
EelgrassMarker.on('mouseout', function() {
    EelgrassMarker.closePopup();
});

         //sample Turtle grass
         var TurtleMarker = L.marker([18.5080,122.1482]).addTo(map);
    // Image URL generated by Laravel's asset helper
var imageUrl = "{{ asset('seapics/Turtle.jpg') }}";
var popupContent = `<b>Turtle Grass</b><br><img src="${imageUrl}"  style="width:100px;">`;

TurtleMarker.bindPopup(popupContent, { closeButton: false });

// Add click event listener to the Neptune marker
TurtleMarker.on('click', function() {
    // Redirect to the specified route
    window.open("https://example.com", "_blank");  // Replace with your URL
});

// Add mouseover event listener to the Neptune marker
TurtleMarker.on('mouseover', function() {
    TurtleMarker.openPopup();
});

// Add mouseout event listener to the Neptune marker
TurtleMarker.on('mouseout', function() {
    TurtleMarker.closePopup();
});

 // Sample Neptune grass
 var NeptuneMarker = L.marker([18.4594, 122.1390]).addTo(map);

// Image URL generated by Laravel's asset helper
var imageUrl = "{{ asset('seapics/Neptune.jpg') }}";
var popupContent = `<b>Neptune Grass</b><br><img src="${imageUrl}"  style="width:100px;">`;

NeptuneMarker.bindPopup(popupContent, { closeButton: false });

// Add click event listener to the Neptune marker
NeptuneMarker.on('click', function() {
    // Redirect to the specified route
    window.open("https://example.com", "_blank");  // Replace with your URL
});

// Add mouseover event listener to the Neptune marker
NeptuneMarker.on('mouseover', function() {
    NeptuneMarker.openPopup();
});

// Add mouseout event listener to the Neptune marker
NeptuneMarker.on('mouseout', function() {
    NeptuneMarker.closePopup();
});

</script>


@endsection